
version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: aeee/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db

  frontend:
    image: aeee/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: aeee/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9090:80

