# Generated by Django 3.2.3 on 2024-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='shopping_carts',
            field=models.ManyToManyField(blank=True, related_name='recipes_in_cart', to='recipes.ShoppingCart'),
        ),
    ]
